### PR TITLE
Fix splitting and joining trains

### LINKED ISSUE #41: Trains that split or merge
The NMBS operates several trains which are split into two indepent trains at some point in their journey. The reverse situation also occurs, with two trains merging into one. Splitting or merging always takes place in a station where traveller can (dis)embark the train.

### Splitting

First of all, the train drives the first part of its journey as a whole, during which it is identified by a single identifier, in this case IC4310. When the train splits, one part of the train keeps the identifier (IC4310) for the remaining of its journey. The other part gets a new identifier, in this case (IC4410). Even though it is clear to see that this is one train, even the NMBS website indicates that there are 2 trips. This causes routeplanning to think a transfer is needed, even though travellers can remain seated if they are in the right part of the train. NMBS' own routeplanning takes this into account, but we need a way to determine this for 3rd party routeplanning.  NMBS does not publish data on which carriages travel where.

splitting train
splitting train

IC4310 in trips.txt: 

```220,000095,88____:007::8821006:8832409:13:1102:20180625,Hamont,4310,,5481,,1```

IC4410 in trips.txt:

```225,000297,88____:007::8832409:8831005:9:1152:20180625,Hasselt,4410,,5658,,1```
### Merging
Merging trains are similar, and have different identifiers until they merge. Once they merge, one of the trains will continue to travel with the identifier of one of said two trains. It should be noted that the train which loses its identifier on merging doesn't seem to have platform information. Again, routeplanning will consider this as a transer, even though passengers can remain seated (an thus don't have to transfer). NMBS' own routeplanning takes this into account, but we need a way to determine this for 3rd party routeplanning.

merging train
merging train

### Solutions for routeplanning
A possible solution for this would be to label the common parts of a journey with both trip ids, by publishing two connection objects for each connection, both objects being identical except for the trip/route id.

Another possible solution would be to create an index of splitting trains, where each row contains two identifiers which belong together in one splitting or merging train. This would be less 'intrusive' to the Linked Connections list, and would prevent certain edge cases (splitting Linked Connections into fragments of a certain filesize could cause two "identical" connections to be split over multiple pages, having to combine and check multiple connection objects would be more complicated compared to only checking a list to determine whether a transfer is 'real' or a split/merge during routeplanning).

Current status
- [x] Investigate how the NMBS handles this
- [x] Investigate how this is published in GTFS

This data is not published in GTFS. There doesn't seem to be any field which implies a train split, or that a train drove part of its journey attached to another train.

### PR DESCRIPTION
**Pull request by pietercolpaert**
Work in progress pull request for joining and splitting trains.

Fix #41 

Ended up doing a lot of other things as well:
 * Better and faster tests
 * Rewrote the connection builder to promises
 * stop_times.txt to connections.txt is now a preprocessing phase in gtfs2lc-sort
 * Rewrote the TripsDB to a StreamIterator. Therefore, the trips.txt needs to be ordered in the same way as connections.txt
 * Elaborated about this in the README.md

### CODE REVIEW

File: lib/ConnectionsBuilder.js [hunk 1]
```diff
@@ -11,6 +11,7 @@ var ConnectionsBuilder = function (tripsdb, servicesdb, routesdb) {
   this._tripsdb = tripsdb;
   this._servicesdb = servicesdb;
   this._routesdb = routesdb;
+  //List of potentially splitting trip ids. If they all of a sudden appear alone, we need to give them a link to the previous connection.
```
Comment (pietercolpaert) [inline lib/ConnectionsBuilder.js]:
```suggestion
 ```

Remove this line
